CREATE TABLE dbo.carboncode
(
timestamp as datetime,
project_name varchar(100),
run_id float,
duration float,
emissions float,
emissions_rate,
cpu_power float,
gpu_power float,
ram_power float,
cpu_energy float,
gpu_energy float,
ram_energy float,
energy_consumed,
country_name varchar(100),
country_iso_code varchar(100),
region varchar(100),
cloud_provider varchar(100),
cloud_region varchar(100),
os varchar(100),
python_version varchar(100),
cpu_count varchar(100),
cpu_model varchar(100),
gpu_count varchar(100),
gpu_model varchar(100),
longitude varchar(100),
latitude varchar(100),
ram_total_size float,
tracking_mode varchar(100),
on_cloud varchar(100)
)
